# Generated by Django 2.2.5 on 2019-09-04 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid1, unique=True),
        ),
    ]
